name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tests
        run: PYTHONPATH=. pytest tests/

      - name: Run Trivy (SCA Analysis)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Run Semgrep (SAST)
        run: semgrep --config=auto .

  dast:
  runs-on: ubuntu-latest
  needs: build
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Start FastAPI App
      run: |
        uvicorn src.main:app --host 0.0.0.0 --port 8000 &
        # Wait for the API to be ready by checking the /docs endpoint
        for i in $(seq 1 10); do
          if curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/docs | grep "200"; then
            echo "FastAPI app is ready"
            break
          fi
          echo "Waiting for FastAPI app... ($i/10)"
          sleep 2
        done
        if ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/docs | grep "200"; then
          echo "Error: FastAPI app did not start in time"
          exit 1
        fi

    - name: Run OWASP ZAP Scan
      run: |
        docker run --rm -v $(pwd):/zap/wrk/ owasp/zap2docker-weekly zap-baseline.py -t http://localhost:8000 -a -r zap-report.html
      continue-on-error: true # Allow the job to continue even if ZAP finds issues

    - name: Upload ZAP Report
      uses: actions/upload-artifact@v4
      with:
        name: ZAP Report
        path: zap-report.html
